### ISSUE TITLE
Please release the fix "Ensure float reti\urntype throught get_fdata()" on PyPI

### ISSUE THREAD

**Issue by pozzs** [DiedrichsenLab/SUITPy#9]
Fresh install with newest nibabel version throws: ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata()

I saw this is fixed in commit 62786952f43f294ea1a93e307a05bde07c948a36, but there's no new release yet on PyPI, as far I can see.

Thank you for developing SUITpy!

**Comment by jdiedrichsen** [comment]
Thank you - 
Yes, a new version 1.3.1 has been now released addressing this. 
Joern
